apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: gusrochada/aggregator-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  type: ClusterIP
  selector:
    app: aggregator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000