apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
        - name: analyzer
          image: gusrochada/analyzer-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: analyzer-service
spec:
  type: ClusterIP
  selector:
    app: analyzer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
